# Generated by Django 4.2.11 on 2024-08-03 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='construtora',
            options={'verbose_name_plural': 'construtoras'},
        ),
        migrations.AlterField(
            model_name='condominio',
            name='construtora',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='login.construtora'),
        ),
    ]
