# Generated by Django 4.2.11 on 2024-08-04 16:50

from django.db import migrations, models
import login.models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_alter_construtora_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='condominio',
            name='nro_acad',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='condominio',
            name='nro_andares',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='condominio',
            name='nro_apt',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='condominio',
            name='nro_blocos',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='condominio',
            name='nro_lazer',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='condominio',
            name='nro_pisc',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='CPF',
            field=models.CharField(default=1, max_length=11, validators=[login.models.validate_cpf]),
            preserve_default=False,
        ),
    ]
