# Generated by Django 4.2.11 on 2024-08-04 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_notpessoa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notpessoa',
            old_name='CPF',
            new_name='cpf',
        ),
        migrations.RenameField(
            model_name='pessoa',
            old_name='CPF',
            new_name='cpf',
        ),
    ]
