# Generated by Django 4.2.11 on 2024-08-04 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_rename_cpf_notpessoa_cpf_rename_cpf_pessoa_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='notpessoa',
            name='andar',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='notpessoa',
            name='apt',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='notpessoa',
            name='bloco',
            field=models.IntegerField(default=1),
        ),
    ]
