# Generated by Django 5.0.7 on 2024-08-06 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0011_delete_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notpessoa',
            name='email',
            field=models.EmailField(max_length=200),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='email',
            field=models.EmailField(max_length=200),
        ),
    ]
