# Generated by Django 5.0.7 on 2024-08-11 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0012_alter_notpessoa_email_alter_pessoa_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='condominio',
            name='nro_acad',
        ),
        migrations.RemoveField(
            model_name='condominio',
            name='nro_pisc',
        ),
        migrations.AddField(
            model_name='condominio',
            name='has_acad',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='condominio',
            name='has_pisc',
            field=models.BooleanField(default=False),
        ),
    ]
