# Generated by Django 5.0.7 on 2024-08-11 21:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0014_arealazer_reserva'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arealazer',
            name='nome',
        ),
        migrations.AddField(
            model_name='arealazer',
            name='fim',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name='arealazer',
            name='inicio',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name='arealazer',
            name='numb',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='arealazer',
            name='pessoa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='areas_lazer_pessoa', to='login.pessoa'),
        ),
        migrations.AlterField(
            model_name='arealazer',
            name='condominio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas_lazer_condominio', to='login.condominio'),
        ),
        migrations.DeleteModel(
            name='Reserva',
        ),
    ]
