# Generated by Django 5.0.7 on 2024-08-11 21:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0015_remove_arealazer_nome_arealazer_fim_arealazer_inicio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arealazer',
            name='fim',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='arealazer',
            name='inicio',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
