# Generated by Django 5.0.7 on 2024-08-11 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0016_alter_arealazer_fim_alter_arealazer_inicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arealazer',
            name='fim',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='arealazer',
            name='inicio',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
