# Generated by Django 5.0.7 on 2024-08-11 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0018_rename_numb_arealazer_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arealazer',
            name='fim',
        ),
        migrations.AddField(
            model_name='arealazer',
            name='tempo',
            field=models.IntegerField(default=0),
        ),
    ]
