# Generated by Django 5.0.7 on 2024-08-11 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0020_alter_arealazer_inicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arealazer',
            name='inicio',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
