# Generated by Django 5.0.7 on 2024-08-11 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0021_alter_arealazer_inicio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arealazer',
            old_name='inicio',
            new_name='start',
        ),
    ]
