# Generated by Django 5.0.7 on 2024-08-11 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0023_rename_start_arealazer_fim_rename_num_arealazer_numb_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arealazer',
            old_name='numb',
            new_name='num',
        ),
    ]
