# Generated by Django 5.0.7 on 2024-08-11 22:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0024_rename_numb_arealazer_num'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='arealazer',
            options={'verbose_name_plural': 'areas de lazer'},
        ),
        migrations.AlterField(
            model_name='arealazer',
            name='fim',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='arealazer',
            name='inicio',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
