# Generated by Django 4.2.11 on 2024-08-12 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0026_arealazer_bloqueado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='sindico',
            field=models.BooleanField(default=False, verbose_name='Síndico'),
        ),
    ]
