# Generated by Django 4.2.11 on 2024-08-12 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0027_alter_pessoa_sindico'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Relatorio',
        ),
    ]
