# Generated by Django 5.0.7 on 2024-08-09 02:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0012_alter_notpessoa_email_alter_pessoa_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assembleia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('data_inicio', models.DateTimeField(blank=True, null=True)),
                ('data_finalizacao', models.DateTimeField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('criada', 'Criada'), ('iniciada', 'Iniciada'), ('finalizada', 'Finalizada')], default='criada', max_length=10)),
                ('condominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.condominio')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='login.pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='Pauta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('assembleia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pautas', to='assembleia.assembleia')),
            ],
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resumo', models.TextField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('assembleia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='assembleia.assembleia')),
            ],
        ),
        migrations.CreateModel(
            name='Votacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voto_sim', models.IntegerField(default=0)),
                ('voto_nao', models.IntegerField(default=0)),
                ('voto_abstencao', models.IntegerField(default=0)),
                ('pauta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votacoes', to='assembleia.pauta')),
            ],
        ),
    ]
