# Generated by Django 5.0.7 on 2024-08-09 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assembleia', '0002_alter_assembleia_criado_por'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='votacao',
            name='pauta',
        ),
        migrations.RemoveField(
            model_name='assembleia',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='votacao',
            name='voto_abstencao',
        ),
        migrations.AddField(
            model_name='registro',
            name='data_finalizacao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='votacao',
            name='assembleia',
            field=models.ForeignKey(default=666, on_delete=django.db.models.deletion.CASCADE, related_name='votos', to='assembleia.assembleia'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='votacao',
            name='titulo',
            field=models.CharField(default=666, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registro',
            name='data_criacao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Requisicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.CharField(max_length=2000)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('assembleia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisicoes', to='assembleia.assembleia')),
            ],
        ),
        migrations.DeleteModel(
            name='Pauta',
        ),
    ]
