# Generated by Django 5.0.7 on 2024-08-09 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assembleia', '0004_alter_assembleia_status'),
        ('login', '0012_alter_notpessoa_email_alter_pessoa_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escolha', models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=3)),
                ('morador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.pessoa')),
                ('votacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votos', to='assembleia.votacao')),
            ],
            options={
                'unique_together': {('votacao', 'morador')},
            },
        ),
    ]
