# Generated by Django 5.0.7 on 2024-08-09 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assembleia', '0005_voto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='votacao',
            name='voto_nao',
        ),
        migrations.RemoveField(
            model_name='votacao',
            name='voto_sim',
        ),
        migrations.CreateModel(
            name='OpcaoVotacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('votos', models.IntegerField(default=0)),
                ('votacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opcoes_votacao', to='assembleia.votacao')),
            ],
        ),
        migrations.AddField(
            model_name='votacao',
            name='opcoes',
            field=models.ManyToManyField(related_name='votacoes', to='assembleia.opcaovotacao'),
        ),
    ]
