# Generated by Django 5.0.7 on 2024-08-10 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assembleia', '0006_remove_votacao_voto_nao_remove_votacao_voto_sim_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voto',
            name='escolha',
        ),
        migrations.AddField(
            model_name='voto',
            name='opcao',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='assembleia.opcaovotacao'),
            preserve_default=False,
        ),
    ]
