# Generated by Django 5.0.7 on 2024-08-10 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assembleia', '0007_remove_voto_escolha_voto_opcao'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='detalhes_votacoes',
            field=models.TextField(default=666),
            preserve_default=False,
        ),
    ]
