# Generated by Django 4.2.11 on 2024-08-12 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assembleia', '0008_registro_detalhes_votacoes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='assembleia.registro')),
            ],
        ),
    ]
