# Generated by Django 4.2.11 on 2024-08-12 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assembleia', '0009_ata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ata',
            name='registro',
        ),
        migrations.AddField(
            model_name='registro',
            name='ata',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ata', to='assembleia.ata'),
        ),
    ]
